Improvements to Bash style and stick certain packages at versions that work when installing software.

diff --git a/bash_functions_build_software b/bash_functions_build_software
--- a/bash_functions_build_software
+++ b/bash_functions_build_software
@@ -30,7 +30,7 @@ build-software () {
     # different version than the curren Debian
 
     # assumes I'm in directory with appropriate subdirectories
-    sudo true || { echo "Failed to sudo!"; return 1; }
+    sudo true || { echo 'Failed to sudo!'; return 1; }
     # at least for now, download and build a few select pieces of software
     [[ ! -d "$HOME/cic-external-vcs" ]] && mkdir -p "$HOME/cic-external-vcs"
     pushd . >/dev/null
@@ -76,7 +76,7 @@ build-software-zathura () {
     ################################################################################
     h2 "girara"
     [[ ! -d "girara-external" ]] && { yell "Directory girara-external not found!"; return 1; }
-    sudo true || { echo "Failed to sudo!"; return 1; }
+    sudo true || { echo 'Failed to sudo!'; return 1; }
     pushd . >/dev/null
     cd girara-external
     check-host-main && git pull
@@ -85,6 +85,7 @@ build-software-zathura () {
     else
         git checkout --track -b develop origin/develop
     fi
+    git checkout 53b862825d7fdb0618d6b7b8680bc7ef53407925
     [[ -d ./build ]] && \rm -rf ./build
     meson build
     cd build
@@ -92,6 +93,7 @@ build-software-zathura () {
     sudo ninja install
     cd ..
     [[ -d ./build ]] && \rm -rf ./build
+    git checkout develop
     popd >/dev/null
     ################################################################################
     h2 "zathura"
@@ -106,7 +108,7 @@ build-software-zathura () {
     fi
     # TODO: temporary until I upgrade debian, Debian's synctex version not new enough
     # this branch is from April 5th 2018, so other ones can be adjusted accordingly if they cease working
-    # git checkout acf9a3bcc160492d389e77ac8a74a43aa0151503
+    git checkout 9fe07d39d09058a3c8ac5dfdc169cda36ba45896
     [[ -d ./build ]] && \rm -rf ./build
     meson build
     cd build
@@ -130,6 +132,7 @@ build-software-zathura () {
     else
         git checkout --track -b develop origin/develop
     fi
+    git checkout ebdd7185db0421e411b08667e849596a13c5abda
     [[ -d ./build ]] && \rm -rf ./build
     meson build
     cd build
@@ -137,6 +140,7 @@ build-software-zathura () {
     sudo ninja install
     cd ..
     [[ -d ./build ]] && \rm -rf ./build
+    git checkout develop
     popd >/dev/null
     ################################################################################
     h2 "zathura-mupdf"
@@ -151,6 +155,8 @@ build-software-zathura () {
     else
         git checkout --track -b develop origin/develop
     fi
+    # git checkout 43e7027eae61f591b5af3062011156eccad98a5f
+    git checkout 95c830c9f6cfe4ba99535ecfba0a700ceb15a25a
     [[ -d ./build ]] && \rm -rf ./build
     meson build
     cd build
@@ -158,6 +164,7 @@ build-software-zathura () {
     sudo ninja install
     cd ..
     [[ -d ./build ]] && \rm -rf ./build
+    git checkout develop
     popd >/dev/null
     ################################################################################
     h2 "zathura-djvu"
@@ -177,6 +184,7 @@ build-software-zathura () {
     sudo ninja install
     cd ..
     [[ -d ./build ]] && \rm -rf ./build
+    git checkout develop
     popd >/dev/null
     ################################################################################
     h2 "zathura-cb"
@@ -196,6 +204,7 @@ build-software-zathura () {
     sudo ninja install
     cd ..
     [[ -d ./build ]] && \rm -rf ./build
+    git checkout develop
     popd >/dev/null
     ################################################################################
     h2 "zathura-ps"
@@ -215,6 +224,7 @@ build-software-zathura () {
     sudo ninja install
     cd ..
     [[ -d ./build ]] && \rm -rf ./build
+    git checkout develop
     popd >/dev/null
     # because I've had issues with libraries installed until I run this
     sudo ldconfig
@@ -225,7 +235,7 @@ build-software-zathura () {
 #     # build and installs xpdf
 #     h2 "xpdf"
 #     [[ ! -d "xpdf-3.04-external" ]] && yell "Directory xpdf-3.04-external not found!" && return 1
-#     sudo true || { echo "Failed to sudo!"; return 1; }
+#     sudo true || { echo 'Failed to sudo!'; return 1; }
 #     pushd . >/dev/null
 #     cd xpdf-3.04-external
 #     make clean
@@ -321,11 +331,13 @@ diff -ru mupdf-clean-external/platform/wasm/Makefile mupdf-modify-external/platf
  wasm: $(MUPDF_JS) $(MUPDF_WASM)
 EOF
     # builds and installs mupdf
+    # TODO: some of the commands below are probably excessive
     h2 "mupdf"
     [[ ! -d "mupdf-external" ]] && yell "Directory mupdf-external not found!" && return 1
-    sudo true || { echo "Failed to sudo!"; return 1; }
+    sudo true || { echo 'Failed to sudo!'; return 1; }
     pushd . >/dev/null
     cd mupdf-external
+    git checkout b1cc2167d698404014d79b9f3794af03312c7ec6
     make clean
     git reset --hard HEAD
     patch -p1 <<< "$MUPDFPATCH"
@@ -341,6 +353,8 @@ EOF
     # undo the patch
     git reset --hard HEAD
     make clean
+    # get to master in case I checked out wierd branch
+    git checkout master
     popd >/dev/null
 }
 
@@ -348,7 +362,7 @@ build-software-feh () {
     # builds and installs the feh image viewer
     h2 "feh"
     [[ ! -d "feh-external" ]] && yell "Directory feh-external not found!" && return 1
-    sudo true || { echo "Failed to sudo!"; return 1; }
+    sudo true || { echo 'Failed to sudo!'; return 1; }
     # must be in proper directory
     pushd . >/dev/null
     cd feh-external
@@ -362,7 +376,7 @@ build-software-feh () {
 build-software-yacreader () {
     h2 "unarr (for yacreader)"
     [[ ! -d "unarr-external" ]] && yell "Directory unarr-external not found!" && return 1
-    sudo true || { echo "Failed to sudo!"; return 1; }
+    sudo true || { echo 'Failed to sudo!'; return 1; }
     pushd . >/dev/null
     cd unarr-external
     [[ -d "build" ]] && rm -rf build
@@ -391,7 +405,7 @@ build-software-dockapps () {
     # https://unix.stackexchange.com/questions/67781/use-shared-libraries-in-usr-local-lib
     h2 "libdockapps"
     [[ ! -d "dockapps-external" ]] && yell "Directory dockapps-external not found!" && return 1
-    sudo true || { echo "Failed to sudo!"; return 1; }
+    sudo true || { echo 'Failed to sudo!'; return 1; }
     pushd . >/dev/null
     cd dockapps-external
     check-host-main && git pull
diff --git a/bash_functions_common b/bash_functions_common
--- a/bash_functions_common
+++ b/bash_functions_common
@@ -252,7 +252,7 @@ nmap-host-ports () {
 
 nmap-host-ports-super () {
     # really slowly look for ports open on a host
-    sudo true || { echo "Failed to sudo!"; return 1; }
+    sudo true || { echo 'Failed to sudo!'; return 1; }
     if [[ -z "$1" ]]; then
         yell "Requires argument!"
         return 1
@@ -741,6 +741,23 @@ vcs-check-root-pull-all () {
             # popd >/dev/null
         else
             h1 "Not pulling $dirname"
+        fi
+    done
+}
+
+vcs-check-root-branches-all () {
+    if [[ "$PWD" == "$HOME" ]]; then
+        yell "Cannot run in home directory!!!"
+        return 1
+    fi
+    for dirname in ${PWD}/*; do
+        [[ -d "$dirname" ]] || continue
+        if [[ -d "$dirname/.git" ]]; then
+            h1 "Checking $dirname/.git"
+            pushd . >/dev/null
+            cd "$dirname"
+            git branch -a
+            popd >/dev/null
         fi
     done
 }
@@ -1527,36 +1544,6 @@ grep-commands () {
     alias | grep -- "$1"
 }
 
-sync-remove-source-1 () {
-    # rsync and remove source, but also backup just in case
-    # TODO: better interface and safety
-    if [[ ! -d "$2" ]]; then
-        yell "Empty directory argument!!!"
-        return 1
-    fi
-    # TODO: check here!
-    if ssh "$1" true; then
-        msg "Incoming from $1"
-        local BACKUPDIR="rsync-backups-$1-$(date-time-stamp)"
-        rsync --progress --archive --checksum --backup --backup-dir="$BACKUPDIR" --rsh='ssh' --remove-source-files "$1:$2/" .
-        # will cause error if there are no backups
-        rmdir --ignore-fail-on-non-empty "$BACKUPDIR"
-    else
-        warn "Hostname $1 not found!"
-    fi
-}
-
-# TODO: unused
-sync-check-source () {
-    # check before running sync-remove-source-1 with same arguments
-    if ssh "$1" true; then
-        # TODO: make explicitly that contents of that directory come into current directory
-        rsync --verbose --checksum --progress --archive  --rsh='ssh' "$1:$2/" .
-    else
-        warn "Hostname $1 not found!"
-    fi
-}
-
 vcs-incoming () {
     # see what would be changed with a git pull
     h2 "The log: "
@@ -1625,7 +1612,8 @@ youtube-normalize-volume () {
     # global function to normalize volume in youtube windows
     # often tied to a hotkey
     local CURRENTWINDOW=$(xdotool getwindowfocus)
-    xdotool search --name youtube | while IFS= read -r line; do
+    local LINES=$(xdotool search --name youtube)
+    while IFS= read -r line; do
         if [[ -n "$line" ]] && xdotool search --class conkeror | grep --color=never -- "$line" >/dev/null; then
             xdotool windowfocus --sync "$line"
             xdotool windowactivate --sync "$line"
@@ -1633,7 +1621,7 @@ youtube-normalize-volume () {
             sleep 0.05
             conkeror-batch -P default -f youtube-normalize-volume
         fi
-    done
+    done <<< "$LINES"
     # TODO: very arbitrary, perhaps wait for something to return
     sleep 0.05
     xdotool windowactivate --sync "$CURRENTWINDOW"
@@ -1678,7 +1666,7 @@ benchmark-compression-gzip () {
     # TODO: this isn't what is wanted for benchmarking extremely large things that might fill up the disk
     mkdir -p "$HOME/tmp"
     du -sh "$1"
-    local THETEMPFILE=$(mktemp "$HOME/tmp/tmp-benchmark-compression-XXXXXXXXXX" --suffix=.tgz)
+    local THETEMPFILE=$(mktemp --suffix=.tgz -- "$HOME/tmp/tmp-benchmark-compression-XXXXXXXXXX")
     time {
         tar --create --file - "$1" | gzip -1 > "$THETEMPFILE"
     }
@@ -1697,7 +1685,7 @@ benchmark-compression-bzip2 () {
     # TODO: this isn't what is wanted for benchmarking extremely large things that might fill up the disk
     mkdir -p "$HOME/tmp"
     du -sh "$1"
-    local THETEMPFILE=$(mktemp "$HOME/tmp/tmp-benchmark-compression-XXXXXXXXXX" --suffix=.tar.bz2)
+    local THETEMPFILE=$(mktemp --suffix=.tar.bz2 -- "$HOME/tmp/tmp-benchmark-compression-XXXXXXXXXX")
     time {
         tar --create --file - "$1" | bzip2 -9 > "$THETEMPFILE"
     }
@@ -1716,7 +1704,7 @@ benchmark-compression-lz4 () {
     # TODO: this isn't what is wanted for benchmarking extremely large things that might fill up the disk
     mkdir -p "$HOME/tmp"
     du -sh "$1"
-    local THETEMPFILE=$(mktemp "$HOME/tmp/tmp-benchmark-compression-XXXXXXXXXX" --suffix=.tar.lz4)
+    local THETEMPFILE=$(mktemp --suffix=.tar.lz4 -- "$HOME/tmp/tmp-benchmark-compression-XXXXXXXXXX")
     time {
         tar --create --file - "$1" | lz4 -1 > "$THETEMPFILE"
     }
@@ -1734,7 +1722,7 @@ benchmark-compression-lzop () {
     # TODO: this isn't what is wanted for benchmarking extremely large things that might fill up the disk
     mkdir -p "$HOME/tmp"
     du -sh "$1"
-    local THETEMPFILE=$(mktemp "$HOME/tmp/tmp-benchmark-compression-XXXXXXXXXX" --suffix=.tar.lzop)
+    local THETEMPFILE=$(mktemp --suffix=.tar.lzop -- "$HOME/tmp/tmp-benchmark-compression-XXXXXXXXXX")
     time {
         tar --create --file - "$1" | lzop -6 > "$THETEMPFILE"
     }
@@ -1752,7 +1740,7 @@ benchmark-compression-rzip () {
     # TODO: this isn't what is wanted for benchmarking extremely large things that might fill up the disk
     mkdir -p "$HOME/tmp"
     du -sh "$1"
-    local THETEMPFILE=$(mktemp "$HOME/tmp/tmp-benchmark-compression-XXXXXXXXXX" --dry-run --suffix=.tar.rz)
+    local THETEMPFILE=$(mktemp --dry-run --suffix=.tar.rz -- "$HOME/tmp/tmp-benchmark-compression-XXXXXXXXXX")
     time {
         tar --create --file - "$1" > test.tar
         rzip -3 test.tar -o "$THETEMPFILE"
@@ -1772,7 +1760,7 @@ benchmark-compression-rzip () {
 # benchmark-compression-lrzip () {
 #     # benchmark lzip compression
 #     du -sh "$1"
-#     local THETEMPFILE=$(mktemp tmp-benchmark-compression-XXXXXXXXXX --dry-run --suffix=.tar.lrzip)
+#     local THETEMPFILE=$(mktemp --dry-run --suffix=.tar.lrzip -- tmp-benchmark-compression-XXXXXXXXXX)
 #     time {
 #         lrzip --level 9 "$1" --outfile "$THETEMPFILE"
 #     }
@@ -1790,7 +1778,7 @@ benchmark-compression-lzip () {
     # TODO: this isn't what is wanted for benchmarking extremely large things that might fill up the disk
     mkdir -p "$HOME/tmp"
     du -sh "$1"
-    local THETEMPFILE=$(mktemp "$HOME/tmp/tmp-benchmark-compression-XXXXXXXXXX" --suffix=.tar.lzip)
+    local THETEMPFILE=$(mktemp --suffix=.tar.lzip -- "$HOME/tmp/tmp-benchmark-compression-XXXXXXXXXX")
     time {
         tar --create --file - "$1" | lzip -9 > "$THETEMPFILE"
     }
@@ -1808,7 +1796,7 @@ benchmark-compression-xz () {
     # TODO: this isn't what is wanted for benchmarking extremely large things that might fill up the disk
     mkdir -p "$HOME/tmp"
     du -sh "$1"
-    local THETEMPFILE=$(mktemp "$HOME/tmp/tmp-benchmark-compression-XXXXXXXXXX" --suffix=.tar.xz)
+    local THETEMPFILE=$(mktemp --suffix=.tar.xz -- "$HOME/tmp/tmp-benchmark-compression-XXXXXXXXXX")
     time {
         tar --create --file - "$1" | xz -9 > "$THETEMPFILE"
     }
@@ -1827,7 +1815,7 @@ benchmark-compression-zip () {
     # TODO: this isn't what is wanted for benchmarking extremely large things that might fill up the disk
     mkdir -p "$HOME/tmp"
     du -sh "$1"
-    local THETEMPFILE=$(mktemp "$HOME/tmp/tmp-benchmark-compression-XXXXXXXXXX" --dry-run --suffix=.zip)
+    local THETEMPFILE=$(mktemp --dry-run --suffix=.zip -- "$HOME/tmp/tmp-benchmark-compression-XXXXXXXXXX")
     time {
         zip "$THETEMPFILE" "$1"
     }
@@ -2242,7 +2230,7 @@ tar-bzip2-remove () {
     fi
     # check if successful, need temp files
     # https://stackoverflow.com/questions/1550933/catching-error-codes-in-a-shell-pipe
-    local THETEMPFILE=$(mktemp "$HOME/tmp/tmp-bzip-remove-XXXXXXXXXX" --suffix=.tar)
+    local THETEMPFILE=$(mktemp --suffix=.tar -- "$HOME/tmp/tmp-bzip-remove-XXXXXXXXXX")
     echo "Tarring $1 to $THETEMPFILE..."
     time {
         tar --create --file - "$1" > "$THETEMPFILE"
@@ -2279,6 +2267,21 @@ ssh-check-host () {
     nc -z "$1" 22 >/dev/null
 }
 
+ssh-check-host-login () {
+    # check if an ssh host port 22 is alive
+    if [[ -z "$1" ]]; then
+        return 1
+    fi
+    if nc -z "$1" 22 >/dev/null 2>&1; then
+        return 0
+    elif ssh "$1" true >/dev/null 2>&1; then
+        return 0
+    else
+        return 1
+    fi
+}
+
+# TODO: more verbose
 ssh-check-host-verbose () {
     # check if an ssh host port 22 is alive but be verbose
     if [[ -z "$1" ]];then
diff --git a/launch-emacsclient b/launch-emacsclient
--- a/launch-emacsclient
+++ b/launch-emacsclient
@@ -27,96 +27,99 @@
 # check if the Emacs server is running, if not start the server
 # see http://www.emacswiki.org/emacs/EmacsClient, although this is outdated
 
-# start emacs daemon if not already started
-# XXXX: avoid starting daemon if computer is configured with systemd service
-# TODO: better way to do this
-# if ! [[ -e "$HOME/.config/systemd/user/emacs.service" ]] && ! ps -ef | grep --color=never '[e]macs --daemon' >/dev/null; then
-if ! ps -ef | grep --color=never '[e]macs --daemon' >/dev/null; then
-    notify-send 'launching emacs --daemon!!!' -t 5000
-    emacs --daemon --no-init-file --load "$HOME/.emacs-cic.el"
-    sleep 3
-fi
-# set up emacsclient command based on nice value
-if [[ $(ulimit -e) -gt "29" ]]; then
-    EMACSCLIENT="nice --adjustment=-10 emacsclient"
-else
-    EMACSCLIENT="emacsclient"
-fi
-if ! ps -ef | grep --color=never '[e]macs --daemon' >/dev/null; then
-    echo "Emacs daemon failed to run!"
-    return 1
-fi
-case $1 in
-    batch )
-        shift
-        ;;
-    capture )
-        shift
-        # check if the server is running, if not start the server
-        # XXXX: select-frame-by-name does not work all the time but the let statement does
-        # (user-position . t)
-        exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh"                --eval "(let ((the-new-frame (make-frame '((name . \"*capture*\") (fullscreen . maximized)  (user-size . t) (window-system . x))))) (select-frame the-new-frame))" "$@"
-        ;;
-    # similar to capture but with different name
-    # TODO: decide have "maximized" as frame name, decide if I really want to do this or if it's useful?
-    maximized )
-        shift
-        # check if the server is running, if not start the server
-        # XXXX: select-frame-by-name does not work all the time but the let statement does
-        exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh"                --eval "(let ((the-new-frame (make-frame '((name . \"*maximized*\") (fullscreen . maximized) (user-size . t) (window-system . x))))) (select-frame the-new-frame))" "$@"
-        ;;
+main () {
+    # start emacs daemon if not already started
+    # XXXX: avoid starting daemon if computer is configured with systemd service
+    # TODO: better way to do this
+    # if ! [[ -e "$HOME/.config/systemd/user/emacs.service" ]] && ! ps -ef | grep --color=never '[e]macs --daemon' >/dev/null; then
+    if ! ps -ef | grep --color=never '[e]macs --daemon' >/dev/null; then
+        notify-send 'launching emacs --daemon!!!' -t 5000
+        emacs --daemon --no-init-file --load "$HOME/.emacs-cic.el"
+        sleep 3
+    fi
+    # set up emacsclient command based on nice value
+    if [[ $(ulimit -e) -gt "29" ]]; then
+        local EMACSCLIENT="nice --adjustment=-10 emacsclient"
+    else
+        local EMACSCLIENT="emacsclient"
+    fi
+    if ! ps -ef | grep --color=never '[e]macs --daemon' >/dev/null; then
+        echo "Emacs daemon failed to run!"
+        return 1
+    fi
+    case $1 in
+        batch )
+            shift
+            ;;
+        capture )
+            shift
+            # check if the server is running, if not start the server
+            # XXXX: select-frame-by-name does not work all the time but the let statement does
+            # (user-position . t)
+            exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh"                --eval "(let ((the-new-frame (make-frame '((name . \"*capture*\") (fullscreen . maximized)  (user-size . t) (window-system . x))))) (select-frame the-new-frame))" "$@"
+            ;;
+        # similar to capture but with different name
+        # TODO: decide have "maximized" as frame name, decide if I really want to do this or if it's useful?
+        maximized )
+            shift
+            # check if the server is running, if not start the server
+            # XXXX: select-frame-by-name does not work all the time but the let statement does
+            exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh"                --eval "(let ((the-new-frame (make-frame '((name . \"*maximized*\") (fullscreen . maximized) (user-size . t) (window-system . x))))) (select-frame the-new-frame))" "$@"
+            ;;
 
-    # similar to capture but with different name
-    # TODO: decide have "*transient*" as frame name, decide if I really want to do this?
-    # TODO: figure out size from window
-    transient )
-        shift
-        # check if the server is running, if not start the server
-        # XXXX: select-frame-by-name does not work all the time but the let statement does
-        exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh"                --eval "(let ((the-new-frame (make-frame '((name . \"*transient*\") (fullscreen . maximized) (user-size . t) (window-system . x))))) (select-frame the-new-frame))" "$@"
-        ;;
-    # no frame,
-    noframe )
-        shift
-        if ! ps -ef | grep --color=never '[e]macs --daemon' >/dev/null; then
-            $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" -c "$@"
-        else
-            emacsclient --no-wait --eval "(if (> (length (frame-list)) 1) 't)" | grep --color=never t
-            if [[ $? = "1" ]]; then
-                exec $EMACSCLIENT --create-frame --no-wait --alternate-editor="launch-emacsclient-fail.sh" "$@"
+        # similar to capture but with different name
+        # TODO: decide have "*transient*" as frame name, decide if I really want to do this?
+        # TODO: figure out size from window
+        transient )
+            shift
+            # check if the server is running, if not start the server
+            # XXXX: select-frame-by-name does not work all the time but the let statement does
+            exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh"                --eval "(let ((the-new-frame (make-frame '((name . \"*transient*\") (fullscreen . maximized) (user-size . t) (window-system . x) (auto-raise t) (wait-for-wm t))))) (select-frame the-new-frame))" "$@"
+            ;;
+        # no frame,
+        noframe )
+            shift
+            if ! ps -ef | grep --color=never '[e]macs --daemon' >/dev/null; then
+                $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" -c "$@"
             else
-                # TODO: why does this seem to be creating a frame anyways?
-                exec $EMACSCLIENT                --no-wait --alternate-editor="launch-emacsclient-fail.sh" "$@"
+                emacsclient --no-wait --eval "(if (> (length (frame-list)) 1) 't)" | grep --color=never t
+                if [[ $? = "1" ]]; then
+                    exec $EMACSCLIENT --create-frame --no-wait --alternate-editor="launch-emacsclient-fail.sh" "$@"
+                else
+                    # TODO: why does this seem to be creating a frame anyways?
+                    exec $EMACSCLIENT                --no-wait --alternate-editor="launch-emacsclient-fail.sh" "$@"
+                fi
             fi
-        fi
-        ;;
-    protocol )
-        shift
-        if ! ps -ef | grep --color=never '[e]macs --daemon' >/dev/null; then
-            $EMACSCLIENT --create-frame --no-wait --alternate-editor="launch-emacsclient-fail.sh" -c "$@"
-        else
-            emacsclient --no-wait --eval "(if (> (length (frame-list)) 1) 't)" | grep --color=never t
-            if [[ $? = "1" ]]; then
-                exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" --create-frame --no-wait "$@"
+            ;;
+        protocol )
+            shift
+            if ! ps -ef | grep --color=never '[e]macs --daemon' >/dev/null; then
+                $EMACSCLIENT --create-frame --no-wait --alternate-editor="launch-emacsclient-fail.sh" -c "$@"
             else
-                exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh"                --no-wait "$@"
+                emacsclient --no-wait --eval "(if (> (length (frame-list)) 1) 't)" | grep --color=never t
+                if [[ $? = "1" ]]; then
+                    exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" --create-frame --no-wait "$@"
+                else
+                    exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh"                --no-wait "$@"
+                fi
             fi
-        fi
-        ;;
-    nohup )
-        shift
-        # TODO: should nohup use exec?
-        # TODO: things highlighted red, if I try to put this in a subshell, is this a real error?
-        nohup $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" --create-frame "$@" &>/dev/null &
-        ;;
-    sameframe )
-        shift
-        exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" "$@"
-        ;;
-    * )
-        exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" --create-frame "$@"
-        ;;
-esac
+            ;;
+        nohup )
+            shift
+            # TODO: should nohup use exec?
+            # TODO: things highlighted red, if I try to put this in a subshell, is this a real error?
+            nohup $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" --create-frame "$@" &>/dev/null &
+            ;;
+        sameframe )
+            shift
+            exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" "$@"
+            ;;
+        * )
+            exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" --create-frame "$@"
+            ;;
+    esac
+}
+main "$@"
 # TODO: do I need these here and do they affect anything?
 export EDITOR="launch-emacsclient -nw"
 export ALTERNATE_EDITOR="launch-emacsclient -nw"
