Many small updates, version bump.  New functions.

diff --git a/bash_functions_stdlib b/bash_functions_stdlib
--- a/bash_functions_stdlib
+++ b/bash_functions_stdlib
@@ -7,7 +7,7 @@
 # Author: Andrew Kroshko
 # Maintainer: Andrew Kroshko <akroshko.public+devel@gmail.com>
 # Created: Fri Mar 27, 2015
-# Version: 20160131
+# Version: 20160526
 # URL: https://github.com/akroshko/bash-stdlib
 #
 # This program is free software: you can redistribute it and/or modify
@@ -448,27 +448,37 @@ harm-bashrc () {
     source ${HOME}/.bashrc
 }
 
+fix-standard-permissions () {
+    true
+}
+
 fix-crypt-permissions () {
     # fix the permissions on a cryptography-relevant directory
     if [[ -z "$1" ]]; then
-        yell "Must have a directory to fix!"
-    fi
-    if [[ -d "$1" ]]; then
-        chmod -R g-rwx "$1"
-        chmod -R o-rwx "$1"
-        chmod u+rwX --recursive "$1"
+        yell "Must have a file or directory to fix!"
     else
-        return 1
-        # XXXX: made silent because used in many places... and missing
-        # crypt directories cause obvious errors elsewhere
-        # warn "Directory $1 does not exist!!!"
+        # fail silently if does not exist
+        if [[ -e "$1" ]]; then
+            if [[ -d "$1" ]]; then
+                chmod --recursive g-rwx "$1"
+                chmod --recursive o-rwx "$1"
+                chmod u+rwX --recursive "$1"
+            else
+                chmod g-rwx "$(readlink -f $1)"
+                chmod o-rwx "$(readlink -f $1)"
+                chmod u+rwX "$(readlink -f $1)"
+            fi
+        fi
     fi
 }
 
 fix-gpg-ssh-permissions () {
+    # TODO: start adding things that might be necessary
+    # TODO: start adding this to the front of critical operations
     # fix the permissions on the standard gpg and ssh directory
     fix-crypt-permissions "${HOME}"/.gnupg
     fix-crypt-permissions "${HOME}"/.ssh
+    fix-crypt-permissions "${HOME}"/.msmtprc
 }
 
 backlight-percentage () {
@@ -479,7 +489,7 @@ backlight-percentage () {
 vcs-check-root () {
     # check if a pull is needed for for child directories if they correspond to common version control systems
     # from https://stackoverflow.com/questions/3258243/git-check-if-pull-needed
-    for dirname in ./*; do
+    for dirname in ${PWD}/*; do
         [[ -d "$dirname" ]] || continue
         # check for various things
         if [[ -d "$dirname/.git" ]]; then
@@ -520,34 +530,37 @@ vcs-check-root () {
     done
 }
 
-vcs-update-all-file-versions () {
-    # should be done before committing public versions
-    if [[ -d "./.git" ]]; then
-       find . -not -path "*git*" -type f -exec bash -c 'source ~/.bash_libenv;vcs-update-file-version "{}"'  \;
-    else
-        echo "Not in a version controlled directory!!!"
-    fi
-}
-
-vcs-update-file-version () {
-    # update versions of all files in current directory tree
-    # file types hardcoded for sanity
-    if [[ -f "$1" ]]
-    then
-        local VERSIONFILE="$1"
-        local FILETYPE=$(file -L "$1")
-        local DATESTAMP=$(date-time-stamp)
-        if [[ $FILETYPE =~ "shell script" ]] || [[ $FILETYPE =~ "Python script" ]];then
-            # script file (with # comment)
-            # -i
-            sed -i "s/^# Version: [[:digit:]]*/# Version: $(date-stamp)/" "$VERSIONFILE"
-        elif [[ $FILETYPE =~ "Lisp/Scheme program" ]] || [[ $VERSIONFILE =~ .*\.el ]]; then
-            # lisp file
-            sed -i "s/^;; Version: [[:digit:]]*/;; Version: $(date-stamp)/" "$VERSIONFILE"
+vcs-update-versions () {
+    # TODO: add fences and safeguards
+    # TODO: search recursively with find command
+    # find . -not -path "*git*" -type f -exec bash -c 'source ~/.bash_libenv;vcs-update-file-version "{}"'  \;
+    for f in ${PWD}/*; do
+        [[ -f "$f" ]] || continue
+        local FILETYPE=$(file -L "$f")
+        # if file starts with #!
+        if [[ "$(head -n 1 $f)" =~ ^\#! ]]; then
+            # hash comment
+            sed -i -e "s/^# Version:.*$/# Version: $(date-stamp)/g" "$f"
+            # if not copyright matches this year
+            if grep "^# Copyright" $f >> /dev/null && ! grep "^# Copyright.*2016" $f >> /dev/null; then
+                warn "Need to update year in $f"
+            fi
+        elif [[ "$FILETYPE" =~ "Lisp/Scheme program" ]] || [[ "$VERSIONFILE" =~ \.el$ ]]; then
+            # lisp
+            sed -i -e "s/^;; Version:.*$/;; Version: $(date-stamp)/g" "$f"
+            # if not copyright matches this year
+            if grep "^;; Copyright" $f >> /dev/null && ! grep "Copyright.*2016" $f >> /dev/null; then
+                warn "Need to update year in $f"
+            fi
+        elif [[ "$FILETYPE" =~ "LaTeX document" ]]; then
+            # latex
+            sed -i -e "s/^% Version:.*$/% Version: $(date-stamp)/g" "$f"
+            # if not copyright matches this year
+            if ! grep "Copyright.*2016" $f >> /dev/null; then
+                warn "Need to update year in $f"
+            fi
         fi
-    else
-        return 1
-    fi
+    done
 }
 
 fail2ban-check () {
@@ -596,10 +609,10 @@ device-disk-uuid () {
 vcs-diff-public () {
     # diff the "master" with the "public" branch for current directory or all child directories that are git repositories
     # XXXX: git only for now
-    if [[ -d "./.git" ]]; then
+    if [[ -d "${PWD}/.git" ]]; then
         git diff public..master
     else
-        for dirname in ./*; do
+        for dirname in ${PWD}/*; do
             if [[ -d "$dirname/.git" ]]; then
                 pushd . >> /dev/null
                 cd "$dirname"
@@ -685,7 +698,7 @@ harm-id3-audiobook-all () {
     # set up all audiobooks in immediate subdirectories for my player
     # (after appropriate file renaming)
     if dangerous-function-ask; then
-        for d in ./*; do
+        for d in ${PWD}/*; do
             [[ -d "$d" ]] || continue
             pushd . >> /dev/null
             cd "${d}"
@@ -709,7 +722,7 @@ harm-id3-genre-as-audiobook () {
 harm-id3-name-as-filename () {
     # make track name correspond to filename
     if dangerous-function-ask; then
-        for F in ./*.mp3; do
+        for F in ${PWD}/*.mp3; do
             local BNAME="${f%%.mp3}"
             # XXXX: basename doesn't work with comma in filename
             BNAME="${bname##*/}"
@@ -724,7 +737,7 @@ harm-id3-alphabetical-track () {
         # totals cause confusion
         eyeD3 --track-total=0 *.mp3
         local COUNT=1
-        for F in ./*.mp3; do
+        for F in ${PWD}/*.mp3; do
             eyeD3 --to-v2.4 --track=$(printf "%03d\n" $COUNT) "$F"
             let COUNT+=1
         done
@@ -859,7 +872,7 @@ vcs-clone-to-bare () {
     # https://stackoverflow.com/questions/4142936/git-clone-from-local-to-remote
     # TODO: need to add a file before I can do anything
     # TODO: this is my own check for my own system, need to generalize
-    if check-host-main && [[ -d ./"$1" ]]; then
+    if check-host-main && [[ -d ${PWD}/"$1" ]]; then
         local REALPATH="$(realpath $1)"
         REALPATH=${REALPATH%/}
         if [[ -e "$REALPATH".git ]]
@@ -1441,7 +1454,7 @@ wget-download-canmatrix2 () {
 wget-current-canmatrix () {
     # expect to take about 16*((16 * 12) + 60) per large grid = 4032min per large numbered grid
     # generally run this on my server to an external hard drive at ~/mnt
-    local URLS=("ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/083/c" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/083/d" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/083/e" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/083/f" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/083/g" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/083/h" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/083/i" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/083/j" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/083/k" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/083/l" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/083/m" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/083/n" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/083/o" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/083/p")
+    local URLS=("ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/094/a" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/094/b" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/094/c" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/094/d" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/094/e" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/094/f" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/094/g" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/094/h" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/094/i" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/094/j" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/094/k" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/094/l" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/094/m" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/094/n" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/094/o" "ftp://ftp2.cits.rncan.gc.ca/pub/canmatrix2/50k_tif/094/p")
     if ! type send-returncode-mail >> /dev/null; then
         warn "No text message progress reports, send-returncode-mail function not configured."
         alias send-returncode-mail="false"
@@ -1477,9 +1490,85 @@ wget-current-canmatrix () {
     fi
 }
 
+add-timestamp-head-of-all-files () {
+    for f in ${PWD}/*; do
+        [[ -f "$f" ]] || continue
+        [[ ! "$(basename $f)" =~ [0-9]{14}--.* ]] || continue
+        echo "Moving $(basename $f)"
+        mv "$(basename $f)" "$(stat $(basename $f) | grep Modify: | sed -e 's/Modify: //' | sed -e 's/-//g' | sed -e 's/://g' | sed -e 's/\..*//g' | sed -e 's/ //g')--$(basename $f)"
+    done
+}
+
 wget-check-log () {
     # do a quick check of a log file to make sure everything is saved properly
     cat "$1" | grep saved | grep -v listing
+}
+
+read-mail () {
+    less /var/spool/mail/${USERNAME}
+}
+
+gpg-decrypt () {
+    gpg --batch --no-verbose --quiet --decrypt "$1" 2>/dev/null
+}
+
+preview-current-directory () {
+    if [[ -n "$1" ]]; then
+        pushd . >> /dev/null
+        cd "$1"
+    fi
+    local screenheight=0
+    # get maximum screen height
+    for z in $(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2); do
+        if [[ $(( $z > $screenheight )) == 1 ]]; then
+            screenheight=$z
+        fi
+    done
+    local previewheight=$(( $screenheight / 2 ))
+    msg "Using preview height: $previewheight"
+    for f in ${PWD}/*; do
+        if [[ "$f" =~ \.jpg$ && "$f" =~ \.jpeg$ && "$f" =~ \.tif$ && "$f" =~ \.tiff$ ]]; then
+            fthumbnail=/home/akroshko/tmp/cic-thumbnail-preview/$(md5sum "$f" | awk '{ print $1 }').png
+            if [[ ! -f "$fthumbnail" ]]; then
+                msg "Previewing: $f"
+                convert -thumbnail x"$previewheight" -background white -alpha remove "$f" "$fthumbnail" &
+            else
+                msg "Already previewed: $f"
+            fi
+        elif [[ "$f" =~ \.pdf ]]; then
+            fthumbnail=/home/akroshko/tmp/cic-thumbnail-preview/$(md5sum "$f" | awk '{ print $1 }').png
+            fthumbnailfirst=/home/akroshko/tmp/cic-thumbnail-preview/$(md5sum "$f" | awk '{ print $1 }')-0.png
+            if [[ ! -f "$fthumbnailfirst" ]]; then
+                msg "Previewing: $f"
+                convert -thumbnail x"$previewheight" -background white -alpha remove "$f"[0-4] "$fthumbnail" &
+            else
+                msg "Already previewed: $f"
+            fi
+        fi
+        # sleep if too many jobs
+        jobs=1000
+        while [[ $jobs -gt 8 ]]; do
+              jobs=$(pgrep 'convert' | wc -l)
+              sleep 0.1
+        done
+    done
+    if [[ -n "$1" ]]; then
+        popd >> /dev/null
+    fi
+}
+
+svg2png-hq () {
+    if [[ -z "$1" ]]; then
+        yell "No input!"
+        return 1
+    fi
+    OUTPUT="${1%%.svg}.png"
+    if [[ -f "$OUTPUT" ]]; then
+        yell "Output $OUTPUT already exists!!!"
+        return 1
+    else
+        convert -density 300 -resize 2000x "$1" "$OUTPUT"
+    fi
 }
 
 ################################################################################
