Added colorized error, message, warn, and heading functions.  Changed to include colors.

diff --git a/bash_library_functions b/bash_library_functions
--- a/bash_library_functions
+++ b/bash_library_functions
@@ -50,9 +50,7 @@ check-host () {
 
 need_new_directory () {
     # create a new directory if it does not already exist
-    if [[ ! -d "$1" ]]; then
-        mkdir -p "$1"
-    fi
+    mkdir -p "$1"
 }
 
 verify-operation () {
@@ -73,10 +71,10 @@ verify-operation () {
                 case $YNT in
                     [Yy]* ) return 0;;
                     [Nn]* ) true;;
-                    * ) echo "Try again!"
+                    * ) warn "Try again!"
                 esac
                 ;;
-            * ) echo "Please answer yes or no.";;
+            * ) warn "Please answer yes or no.";;
         esac
     done
 }
@@ -270,7 +268,7 @@ need_new_symlink () {
     # TODO: overwrite and backup files while killing symlinks
     if [[ -e "$2" && ! -h "$2" ]]; then
         # symlink is a file or something
-        echo "$2: exists but is not a symlink!!!"
+        yell "$2: exists but is not a symlink!!!"
     elif [[ ! -h "$2" ]]; then
         # symlink does not exist at all or is a file
         ln -s "$1" "$2"
@@ -363,14 +361,14 @@ find-broken-symlinks () {
 }
 
 xclip-show-all () {
-    echo "========================================"
-    echo "Primary"
+    h1
+    msg "Primary"
     xclip -o -selection p
-    echo "========================================"
-    echo "Secondary"
+    h1
+    msg "Secondary"
     xclip -o -selection s
-    echo "========================================"
-    echo "Clipboard"
+    h1
+    msg "Clipboard"
     xclip -o -selection c
 }
 
@@ -413,8 +411,9 @@ fgi () {
 }
 
 harm-bash () {
-    # TODO: check for function and is this appropriate
-    killall xbindkeys
+    if ps -ef | grep "xbindkeys" | grep -v grep >> /dev/null; then
+        killall xbindkeys
+    fi
     source ${HOME}/.bash_profile
 }
 
@@ -436,29 +435,29 @@ vcs-check-root () {
         # check for various things
         if [[ -d "$dirname/.git" ]]; then
             # TODO: exclude lines saying [up to date] and just give a summary of branches
-            echo "==== Checking     $dirname/.git ===========================================================================" | cut -c 1-80
+            h1 "Checking $dirname/.git"
             pushd . >> /dev/null
             cd "$dirname"
             git fetch
             git fetch --verbose
-            echo "---- diff origin/master ----------------------------------------" | cut -c 1-40
+            h2 "diff origin/master"
             git diff origin/master --summary
             popd >> /dev/null
         elif [[ -d "$dirname/.hg" ]]; then
-            echo "==== Checking     $dirname/.hg ============================================================================" | cut -c 1-80
+            h1 "Checking $dirname/.hg"
             # TODO: non-functional? I have no remaining hg repos
             # pushd . >> /dev/null
             # cd "$dirname"
             # hg fetch --dry-run --verbose
             # popd >> /dev/null
         elif [[ -d "$dirname/.svn" ]]; then
-            echo "==== Checking     $dirname/.svn ===========================================================================" | cut -c 1-80
+            h1 "Checking $dirname/.svn"
             pushd . >> /dev/null
             cd "$dirname"
             svn status --show-updates
             popd >> /dev/null
         else
-            echo "==== Not checking $dirname ================================================================================" | cut -c 1-80
+            h1 "Not checking $dirname"
         fi
     done
 }
@@ -485,7 +484,7 @@ mount-disk-uuid () {
         return 0
     else
         # TODO: for now I have gnome mount for me
-        echo "Disk not mounted!!!"
+        yell "Disk not mounted!!!"
         return 1
         # # TODO: mount on a temporary directory
         # MOUNTPOINT=$(mktemp -d)
@@ -512,7 +511,7 @@ vcs-diff-public () {
                 pushd . >> /dev/null
                 cd "$dirname"
                 if git rev-parse --verify public >> /dev/null 2>&1; then
-                    echo "==== Checking $dirname ================================================================================" | cut -c 1-80
+                    h1 "Checking $dirname"
                     git diff master..public --stat
                 fi
                 popd >> /dev/null
@@ -526,7 +525,7 @@ vcs-push-github () {
     # XXXX: repository must be setup properly
     git checkout public
     if [[ $? != 0 ]]; then
-        echo "Checkout unsuccessful!"
+        yell "Checkout unsuccessful!"
         return 1
     fi
     git merge --squash -X theirs master
@@ -536,7 +535,7 @@ vcs-push-github () {
         # TODO: add option for quit
         read -p "Use commit message (y/n/q)? " COMMITCORRECT
         if [[ "$COMMITCORRECT" == "q" ]]; then
-            echo "Aborting!"
+            yell "Aborting!"
             git checkout master
             return 1
         fi
@@ -659,74 +658,133 @@ ag-list-packages-only () {
     ag-list-installed | cut -d' ' -f3
 }
 
+
+# the three-fingered claw, see https://stackoverflow.com/questions/1378274/in-a-bash-script-how-can-i-exit-the-entire-script-if-a-certain-condition-occurs
+yell () {
+    echo -e "${BRed}$0${Red}: $*${Color_Off}" >&2
+}
+
+die () {
+    yell "$*"; exit 111
+}
+
+try () {
+    "$@" || die "cannot $*"
+}
+
+warn () {
+    echo -e "${BYellow}$0${Yellow}: $*${Color_Off}" >&2
+}
+
+msg () {
+    echo -e "${BGreen}$0${Green}: $*${Color_Off}" >&2
+}
+
+h1 () {
+    if [[ -z "$*" ]]; then
+        OUTSTR=$(echo "================================================================================" | cut -c 1-80)
+    else
+        OUTSTR=$(echo "==== $* ================================================================================" | cut -c 1-80)
+    fi
+    echo -e "${BWhite}${On_Blue}$OUTSTR${Color_Off}" >&2
+}
+
+h1-end () {
+    if [[ -z "$*" ]]; then
+        OUTSTR=$(echo "" | cut -c 1-80)
+    else
+        OUTSTR=$(echo "$*" | cut -c 1-80)
+    fi
+    echo -e "${BWhite}${On_Blue}<<<<${Color_Off} ${BWhite}$OUTSTR${Color_Off}" >&2
+}
+
+h1-script () {
+    OUTSTR=$(echo "==== Running $(basename $0) ================================================================================" | cut -c 1-80)
+    echo -e "${BWhite}${On_Blue}$OUTSTR${Color_Off}" >&2
+}
+
+h1-script-end () {
+    OUTSTR=$(echo "Finishing $(basename $0)" | cut -c 1-80)
+    echo -e "${BWhite}${On_Blue}<<<<${Color_Off} ${BWhite}$OUTSTR${Color_Off}" >&2
+}
+
+h2 () {
+   if [[ -z "$*" ]]
+    then
+        OUTSTR=$(echo "----------------------------------------" | cut -c 1-60)
+    else
+        OUTSTR=$(echo "---- $* ----------------------------------------" | cut -c 1-60)
+    fi
+    echo -e "${White}${On_Purple}$OUTSTR${Color_Off}" >&2
+}
+
 ################################################################################
 ## set interesting things for bashrc, should these be here or a seperate file?
 ################################################################################
 # https://wiki.archlinux.org/index.php/Color_Bash_Prompt
-# TODO: move this, should not force color prompt for using other bash functions
 # XXXX: is it likely this may clobber other things in the namespace?
 # Reset
-Color_Off='\[\e[0m\]'       # Text Reset
+Color_Off='\e[0m'       # Text Reset
 # Regular Colors
-Black='\[\e[0;30m\]'        # Black
-Red='\[\e[0;31m\]'          # Red
-Green='\[\e[0;32m\]'        # Green
-Yellow='\[\e[0;33m\]'       # Yellow
-Blue='\[\e[0;34m\]'         # Blue
-Purple='\[\e[0;35m\]'       # Purple
-Cyan='\[\e[0;36m\]'         # Cyan
-White='\[\e[0;37m\]'        # White
+Black='\e[0;30m'        # Black
+Red='\e[0;31m'          # Red
+Green='\e[0;32m'        # Green
+Yellow='\e[0;33m'       # Yellow
+Blue='\e[0;34m'         # Blue
+Purple='\e[0;35m'       # Purple
+Cyan='\e[0;36m'         # Cyan
+White='\e[0;37m'        # White
 # Bold
-BBlack='\[\e[1;30m\]'       # Black
-BRed='\[\e[1;31m\]'         # Red
-BGreen='\[\e[1;32m\]'       # Green
-BYellow='\[\e[1;33m\]'      # Yellow
-BBlue='\[\e[1;34m\]'        # Blue
-BPurple='\[\e[1;35m\]'      # Purple
-BCyan='\[\e[1;36m\]'        # Cyan
-BWhite='\[\e[1;37m\]'       # White
+BBlack='\e[1;30m'       # Black
+BRed='\e[1;31m'         # Red
+BGreen='\e[1;32m'       # Green
+BYellow='\e[1;33m'      # Yellow
+BBlue='\e[1;34m'        # Blue
+BPurple='\e[1;35m'      # Purple
+BCyan='\e[1;36m'        # Cyan
+BWhite='\e[1;37m'       # White
 # Underline
-UBlack='\[\e[4;30m\]'       # Black
-URed='\[\e[4;31m\]'         # Red
-UGreen='\[\e[4;32m\]'       # Green
-UYellow='\[\e[4;33m\]'      # Yellow
-UBlue='\[\e[4;34m\]'        # Blue
-UPurple='\e[4;35m\]'        # Purple
-UCyan='\[\e[4;36m\]'        # Cyan
-UWhite='\[\e[4;37m\]'       # White
+UBlack='\e[4;30m'       # Black
+URed='\e[4;31m'         # Red
+UGreen='\e[4;32m'       # Green
+UYellow='\e[4;33m'      # Yellow
+UBlue='\e[4;34m'        # Blue
+UPurple='\e[4;35m'      # Purple
+UCyan='\e[4;36m'        # Cyan
+UWhite='\e[4;37m'       # White
 # Background
-On_Black='\[\e[40m\]'       # Black
-On_Red='\[\e[41m\]'         # Red
-On_Green='\[\e[42m\]'       # Green
-On_Yellow='\[\e[43m\]'      # Yellow
-On_Blue='\[\e[44m\]'        # Blue
-On_Purple='\[\e[45m\]'      # Purple
-On_Cyan='\[\e[46m\]'        # Cyan
-On_White='\[\e[47m\]'       # White
+On_Black='\e[40m'       # Black
+On_Red='\e[41m'         # Red
+On_Green='\e[42m'       # Green
+On_Yellow='\e[43m'      # Yellow
+On_Blue='\e[44m'        # Blue
+On_Purple='\e[45m'      # Purple
+On_Cyan='\e[46m'        # Cyan
+On_White='\e[47m'       # White
 # High Intensity
-IBlack='\[\e[0;90m\]'       # Black
-IRed='\[\e[0;91m\]'         # Red
-IGreen='\[\e[0;92m\]'       # Green
-IYellow='\[\e[0;93m\]'      # Yellow
-IBlue='\[\e[0;94m\]'        # Blue
-IPurple='\[\e[0;95m\]'      # Purple
-ICyan='\[\e[0;96m\]'        # Cyan
-IWhite='\[\e[0;97m\]'       # White
+IBlack='\e[0;90m'       # Black
+IRed='\e[0;91m'         # Red
+IGreen='\e[0;92m'       # Green
+IYellow='\e[0;93m'      # Yellow
+IBlue='\e[0;94m'        # Blue
+IPurple='\e[0;95m'      # Purple
+ICyan='\e[0;96m'        # Cyan
+IWhite='\e[0;97m'       # White
 # Bold High Intensity
-BIBlack='\[\e[1;90m\]'      # Black
-BIRed='\[\e[1;91m\]'        # Red
-BIGreen='\[\e[1;92m\]'      # Green
-BIYellow='\[\e[1;93m\]'     # Yellow
-BIBlue='\[\e[1;94m\]'       # Blue
-BIPurple='\[\e[1;95m\]'     # Purple
-BICyan='\[\e[1;96m\]'       # Cyan
-BIWhite='\[\e[1;97m\]'      # White
+BIBlack='\e[1;90m'      # Black
+BIRed='\e[1;91m'        # Red
+BIGreen='\e[1;92m'      # Green
+BIYellow='\e[1;93m'     # Yellow
+BIBlue='\e[1;94m'       # Blue
+BIPurple='\e[1;95m'     # Purple
+BICyan='\e[1;96m'       # Cyan
+BIWhite='\e[1;97m'      # White
 # High Intensity backgrounds
-On_IBlack='\[\e[0;100m\]'   # Black
-On_IRed='\[\e[0;101m\]'     # Red
-On_IGreen='\[\e[0;102m\]'   # Green
-On_IYellow='\[\e[0;103m\]'  # Yellow
-On_IBlue='\[\e[0;104m\]'    # Blue
-On_IPurple='\[\e[10;95m\]'  # Purple
-On_ICyan='\[\e[0;106m\]'    # Cyan
-On_IWhite='\[\e[0;107m\]'   # White
+On_IBlack='\e[0;100m'   # Black
+On_IRed='\e[0;101m'     # Red
+On_IGreen='\e[0;102m'   # Green
+On_IYellow='\e[0;103m'  # Yellow
+On_IBlue='\e[0;104m'    # Blue
+On_IPurple='\e[10;95m'  # Purple
+On_ICyan='\e[0;106m'    # Cyan
+On_IWhite='\e[0;107m'   # White
